name: my_crew
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  logger: ^1.1.0
  flutter_svg: ^1.1.3
  cached_network_image: ^3.2.1
  image_picker: ^0.8.6
  flutter_screenutil: ^5.5.3+2
  shared_preferences: ^2.0.15
  google_sign_in: ^5.3.3
  google_maps_flutter: ^2.1.12
  geocoding: ^2.0.5
  flutter_rating_bar: ^4.0.1
  # flutter_local_notifications: ^12.0.3
  url_launcher: ^6.1.7
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  pocketbase: 0.5.0
  http: ^0.13.5
  sqflite: ^2.2.2
  file_picker: ^5.2.5
  snippet_coder_utils: ^1.0.12
  flutter_map: ^3.1.0
  flutter_map_marker_cluster: ^1.0.1
  flutter_local_notifications: ^13.0.0
  awesome_notifications: ^0.7.4+1
  provider: ^6.0.5
  path_provider: ^2.0.11
  flutter_chat_ui: ^1.6.6
  webview_flutter: ^4.0.1
  dcdg: ^4.1.0
  # firebase_core: ^2.3.0
  # cloud_firestore: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/
    - assets/gifs/
    - assets/catimage/
    - assets/company/
    - assets/user/

  # example:
  fonts:
    - family: tajwal
      fonts:
        - asset: assets/fonts/tajawal_regular.ttf
        - asset: assets/fonts/tajawal_medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal_bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
